### PR TITLE
Fix/move group by column to left

### LINKED ISSUE #291: Grouping columns should shift group labels to the left
**Current:**
- Group labels are in the middle of the row, with the column label. 
screen shot 2018-01-10 at 4 29 33 pm

Expected:
- Group labels are left aligned and the label off the grouped column has been removed. 
screen shot 2018-01-10 at 4 37 27 pm

### PR DESCRIPTION
**Pull request by limonte**
Fixes #291

### CODE REVIEW

**Comment by alump** [comment]
@limonte - doesn't work when selection column is present

**Comment by alump** [comment]
@limonte - Breaks sorting by the left most column, as it's applied to group text now?

**Comment by alump** [comment]
@limonte - if first column is hidden in grouped by mode it breaks, we need to have logic to update where grouped by value is drawn if first column is hidden

**Comment by alump** [comment]
@limonte - the group by value is still inside what ever rendered the first column has, this will cause issue. Just go to custom rendered example, make the icon column the left most, and then try to group by. We need to find way to render these outside the rendered. Could we do this with dom-if restamp that could check if item has _groupId defined? If it is, then normal renderer would be not be used?

**Comment by limonte** [comment]
I'm closing this in favor of https://github.com/vaadin/px-data-grid/pull/658

**Pull request closed without merging**
